### ISSUE TITLE
Microsoft.Insights need to registered to be able to complete all the steps in LAB08/Task6

### ISSUE THREAD

**Issue by cnschindler** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#55]
# Module: 08
#### Step: 00

Description of issue

To be able to do Task 6, the namespace for Application Insights needs to be registered in the Azure Pass Subscription.

So add the following step at the beginning of task 6 to register microsoft.insights:

Register-AzResourceProvider -ProviderNamespace microsoft.insights

Repro steps:

1.
1.
1.

**Comment by markturpinMSFT** [comment]
In addition, same thing needs to happen for Microsoft.AlertsManagement (needed for Module 11 labs)

Register-AzResourceProvider -ProviderNamespace Microsoft.AlertsManagement

**Comment by polichtm** [comment]
Pls clarify which lab, exercise, task and step you are referring to and what specifically is the error message you are seeing
rgds
Marcin

**Comment by al-lac** [comment]
The error is "The subscription is not registered to use namespace 'microsoft.insights'. See https://aka.ms/rps-not-found for how to register subscriptions."

You first get the error when trying to create a scale rule for Lab 8 in Task 6.

The instructions should be changed to that there is one additional command for Register-AzResourceProvider when creating the resource groups for Lab 8 and 11.

**Comment by markturpinMSFT** [comment]
The issue here is that new Azure Pass subscriptions (and perhaps others) do not come with either resource provider registered by default:

microsoft.insights
Microsoft.AlertsManagement

You can't create a scale rule without the first one (Lab 8/ Task 6/ Step 8) and you can't create an Azure Automation account (lab 11/task 2/ step 4) (i believe it's the automation account, I might be wrong) without the second.  

The labs need a step to check for the registration status of both resource proviers and to register them if not already registered.

I tell my students to register each before the first lab - in some instances it's taken hours to register miccrosoft.insights

**Comment by polichtm** [comment]
updated
rgds
Marcin
