### ISSUE TITLE
AZ-104-MicrosoftAzureAdministrator - Module 8 - Task 1

### ISSUE THREAD

**Issue by Sanket-ST** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#604]
# Module: 08
#### Step: 03 & 13

Description of issue

In **Task 1: Deploy zone-resilient Azure virtual machines by using the Azure portal and an Azure Resource Manager template**, its mentioned to create a virtual machine using the portal first using **Zone 1** in **step 3** & then use the same template to deploy another virtual machine in **Zone 2** by just changing the value of the template parameter **Zone**  to **2** in **step 13**, however, the second virtual machine is still being deployed on **Zone 1** itself & not **Zone 2**

When I connected with MS support team on the same, they too faced the same issue & weren't able to deploy a virtual machine in an alternate zone using template deployment.

Repro steps:

1.
1.
1.

**Comment by mkennten** [comment]
I can confirm that this is what I'm seeing too when running the lab.

**Comment by mkennten** [comment]
This issue seems to be due to a change in the ARM templates. I can repro the same issue in another subscription. The parameter for the Zone used in the parameter file is called Zone while the parameter used at the resource-level for the VM and the Public IP is called Zones.

![image](https://user-images.githubusercontent.com/37703728/192743064-6156bb83-7852-4ca3-8b89-5ca393c1848f.png)
![image](https://user-images.githubusercontent.com/37703728/192743406-5ab7f814-2c0c-4a87-adf0-ba46869d7484.png)

**Comment by Sanket-ST** [comment]
@mkennten The parameter Zone isn't used in the Public IP Adresses & Virtual Machines as well, hence it's taking the default value of zone 1.

Repro steps:

* Add another step to let the user know to make change the **zones** value from **1** to **2** in the Public IP Addresses & Virtual Machines resources.

**Comment by staleycyn** [comment]
@mkennten - Do we know if this bug has been fixed?

**Comment by mkennten** [comment]
@staleycyn - I tested it this morning and the issue persists, no change to the above. I'm not sure if this is a known bug already and unfortunately, I don't have any means of creating a support case currently.

Repo Steps:
1. Deploy a VM into an Availability Zone
2. On the deployment screen click Redeploy
3. Check the ARM template for the use of parameter zone/zones
