### ISSUE TITLE
Not enough permissions to do "Run Command" option. 

### ISSUE THREAD

**Issue by Vincent-MicrosoftTechnicalTrainer-MTT** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#681]
# Module: 07
#### Step: 06

Description of issue

Using cloudslice - the users do not have enough permissions to do "Run Command" option. 

Repro steps:

1.
1.
1.

**Comment by staleycyn** [comment]
I have forwarded this to the lab hoster's support desk.

**Comment by staleycyn** [comment]
Here is the response from the lab hoster. Please contact them directly if the issue persists. 
 
We launched our own lab instance and confirmed the script executed successfully; we are not able to reproduce the user lab issue. If there are students experiencing the issue, please provide the support email the lab instance id. 
 
here are a couple of recommendations we can give if you run into a step or content that halts your progress:
 
1. Backtrack through a few steps to ensure nothing was missed or mis-keyed (commas instead of periods, missed PowerShell commands, a copy/paste that didn't catch everything).
 
2. If you are unable to find the root cause of the issue you can always cancel your current lab and launch a new one as that will give you a fresh environment to use.

support@skillable.zendesk.com
