### ISSUE TITLE
Lab 3c and 3d need values from earlier labs

### ISSUE THREAD

**Issue by autosysops** [MicrosoftLearning/AZ-104-MicrosoftAzureAdministrator#770]
# Module: 3
#### Step: 1

Description of issue
During the step 2 in both lab c and d they assume the lab retained the resources from the previous lab. Some lab providers (for example Skillable) don't retain these resources and therefore the exercises don't work.

Repro steps:

1.
1.
1.

**Comment by autosysops** [comment]
I don't think this solved the issue. Skillable for example creates a new environment for every lab. so even if you completed 3b the data from 3c won't be there anymore.

**Comment by TesterTesterson1004** [comment]
I just took AZ-104 labs 3C & 3D and was able to complete them successfully, I wasn't seeing resources missing....it appeared that the labs had everything they needed (in particular, that first task that re-creates the RG from the previous lab)

You might want to open a support ticket w/Skillable if you can reproduce a specific error or content that the labs requires and 
 is missing or isnt created successfully:  I know for Cloudslice labs, there can sometimes be compromises that need to be made in order to support them.  Also possible there could be intermittent or other errors that block progress but may not be related to the Instructions?
